jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      if: matrix.java == '8'
      uses: gradle/wrapper-validation-action@v2
    - continue-on-error: true
      name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      if: matrix.java == '11'
      name: Check with Error Prone
      run: ./gradlew errorprone clean -Dtoolchain=${{ matrix.toolchain }}
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build -Dtoolchain=${{ matrix.toolchain }}
    - continue-on-error: true
      if: matrix.java == '11'
      name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FlatLaf-build-artifacts
        path: 'flatlaf-*/build/libs

          flatlaf-*/flatlaf-*/build/libs

          !**/*-javadoc.jar

          !**/*-sources.jar

          '
    strategy:
      matrix:
        include:
        - java: 21
          toolchain: 22
        java:
        - 8
        - 11
        - 17
        - 21
        toolchain:
        - ''
  release:
    if: 'github.event_name == ''push'' &&

      startsWith( github.ref, ''refs/tags/'' ) &&

      github.repository == ''JFormDesigner/FlatLaf''

      '
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      name: Release a new stable version to Maven Central
      run: ./gradlew publish :flatlaf-demo:build :flatlaf-theme-editor:build -PskipFonts
        -Prelease -Dorg.gradle.parallel=false
    - continue-on-error: true
      name: Upload demo
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        forceSsl: true
        host: ${{ secrets.FTP_SERVER }}
        localDir: flatlaf-demo/build/libs
        options: --only-newer --no-recursion --verbose=1
        password: ${{ secrets.FTP_PASSWORD }}
        remoteDir: .
        user: ${{ secrets.FTP_USERNAME }}
    - continue-on-error: true
      name: Upload theme editor
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        forceSsl: true
        host: ${{ secrets.FTP_SERVER }}
        localDir: flatlaf-theme-editor/build/libs
        options: --only-newer --no-recursion --verbose=1
        password: ${{ secrets.FTP_PASSWORD }}
        remoteDir: .
        user: ${{ secrets.FTP_USERNAME }}
  snapshot:
    if: 'github.event_name == ''push'' &&

      (github.ref == ''refs/heads/main'' || startsWith( github.ref, ''refs/heads/develop-''
      )) &&

      github.repository == ''JFormDesigner/FlatLaf''

      '
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Publish snapshot to oss.sonatype.org
      run: ./gradlew publish :flatlaf-theme-editor:build -PskipFonts -Dorg.gradle.internal.publish.checksums.insecure=true
        -Dorg.gradle.parallel=false
    - continue-on-error: true
      name: Upload theme editor
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        forceSsl: true
        host: ${{ secrets.FTP_SERVER }}
        localDir: flatlaf-theme-editor/build/libs
        options: --only-newer --no-recursion --verbose=1
        password: ${{ secrets.FTP_PASSWORD }}
        remoteDir: snapshots
        user: ${{ secrets.FTP_USERNAME }}
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
