jobs:
  Fonts:
    if: 'github.event_name == ''push'' &&

      github.repository == ''JFormDesigner/FlatLaf''

      '
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      if: startsWith( github.ref, format( 'refs/tags/fonts/{0}-', matrix.font ) )
        != true
      name: Build with Gradle
      run: ./gradlew :flatlaf-fonts-${{ matrix.font }}:build
    - continue-on-error: true
      env:
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      if: github.ref == 'refs/heads/main' || startsWith( github.ref, 'refs/heads/develop-'
        )
      name: Publish snapshot to oss.sonatype.org
      run: ./gradlew :flatlaf-fonts-${{ matrix.font }}:publish -Dorg.gradle.internal.publish.checksums.insecure=true
    - continue-on-error: true
      env:
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      if: startsWith( github.ref, format( 'refs/tags/fonts/{0}-', matrix.font ) )
      name: Release a new stable version to Maven Central
      run: ./gradlew :flatlaf-fonts-${{ matrix.font }}:build :flatlaf-fonts-${{ matrix.font
        }}:publish -Prelease
    strategy:
      matrix:
        font:
        - inter
        - jetbrains-mono
        - roboto
        - roboto-mono
name: Fonts
on:
  repository_dispatch:
    types: trigger-ga___fonts.yml
