jobs:
  Natives:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v2
    - continue-on-error: true
      name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build-natives --no-daemon
    - continue-on-error: true
      name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FlatLaf-natives-build-artifacts-${{ matrix.os }}
        path: 'flatlaf-core/src/main/resources/com/formdev/flatlaf/natives

          flatlaf-natives/flatlaf-natives-*/build

          '
    strategy:
      matrix:
        os:
        - windows
        - macos
        - ubuntu
name: Native Libraries
on:
  repository_dispatch:
    types: trigger-ga___natives.yml
