jobs:
  snapshot:
    if: github.repository == 'JFormDesigner/FlatLaf'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      env:
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Publish PR snapshot to oss.sonatype.org
      run: './gradlew publish -PskipFonts -Dorg.gradle.internal.publish.checksums.insecure=true
        -Dorg.gradle.parallel=false -Pgithub.event.pull_request.number=${{ github.event.pull_request.number
        }}

        '
name: PR Snapshots
on:
  repository_dispatch:
    types: trigger-ga___pr-snapshots.yml
